server:
  port: 8085

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: kevin-year


# 整合mntityybatis的配置XXXXX
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kevinlee.sharingjdbc.entity